services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: cheapest_plane_ticket_database
    env_file:
      - variables.env
    ports:
      - "1433:1433"
    expose:
      - "1433"
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data: